lesson_11
NataKanyuk/Robot_Dreams pull request #8
Opened 2023-06-11 21:02 UTC by NataKanyuk

2023-06-13 12:56 UTC, RomanIlkiv requested changes

2023-06-13 12:56 UTC, RomanIlkiv commented on lesson_11/index.html
> +      <img src="logo.png" />
don't forget about `alt` attribute

2023-06-13 12:56 UTC, RomanIlkiv commented on lesson_11/index.html
> +            <img src="Orchid .png" />
redundant space before `.png`

2023-06-13 12:56 UTC, RomanIlkiv commented on lesson_11/index.html
> +            <span>ORCHID </span>
here the same

2023-06-13 12:56 UTC, RomanIlkiv commented on lesson_11/index.html
> +            <img src="Peony.png" />
no `alt` attributes anywhere

2023-06-13 12:56 UTC, RomanIlkiv commented on lesson_11/dried flowers.png
move all images to separate folder
and fonts too

2023-06-18 09:58 UTC, NataKanyuk reviewed
I made changes and fixed the error

2023-06-18 10:00 UTC, merged